### ISSUE TITLE
I find the example in the video to be counter intuitive

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/ruby-lecture-fixing-our-broken-program#6]
In order to describe a passing/failing tests, the video in this lab has a test that expects a program to fail. I feel like the the notion of a test failing because the program runs correctly is counter-intuitive to a beginner, and that we could go with a more straightforward way of describing passing/failing tests.

**Comment by pletcher** [comment]
This is a pretty handy thing to get students to think about, though -- it _is_ counter-intuitive, but I'm not sure there's a way around that; and this isn't students' first encounter with testing. (It's early, but they've run through a lab or two at this point.)

@PeterBell thoughts?

**Comment by PeterBell** [comment]
I tend to agree with @matbalez - usually it's "Red-Green-Refactor", and usually when you find code that's broken, you write a test that confirms the behavior that you'd like to see. In this case maybe that some of the puts content was pushed to std-out. Then you run the test, it's red because that doesn't work. You then fix the code and then confirm that the test is now passing. I think that approach could work fine with this video, so my 2c would be that I'd put the video into the backlog of "to re-record", but should probably ask Avi - he may have had a specific reason for taking this approach . . .

**Comment by PeterBell** [comment]
^^^ @pletcher

**Comment by pletcher** [comment]
Ah, hm, I think we're talking about multiple things now.

My understanding was that what was confusing is that the test _worked_ when the code was _broken_.

But, @PeterBell, if I'm reading your comment right, you're suggesting changing it so that the test initially fails (that is, the code is initially functional), and then students refactor (break) the code to get the test to pass.

That might help address some of the confusion -- it at least gets them in the usual flow. And it still gets them used to the idea that you want to test that your code errors out when expected.

So yeah, I wonder if we can add this to the list of videos that could use a revisit.

**Comment by PeterBell** [comment]
Hey @pletcher I _think_ we're talking about the same thing. I agree with Mat that it was confusing that the test passed when the code was broken and therefore I was suggesting we change that so the test initially fails and then the students fixes the code to get the test to pass. If you think about it from a testing perspective, I expect my code to output some strings to stdout. I should test for that. The test will be red because my code doesn't do that and therefore I need to go fix my code. When I do so, the test will then be green. 

So yeah, backlog for re-shoot sounds like a win to me @pletcher - cc @AnnJohn for scheduling/prioritizing

**Comment by PeterBell** [comment]
Just assigned you @AnnJohn - if that's the _wrong_ thing to do in cases like this, just unassign yourself and let me know what you'd like done in the future for issues like these!

**Comment by pletcher** [comment]
Right right, that all sounds good :dancer:

**Comment by maxwellbenton** [comment]
Hi @matbalez,

Thank you for opening this issue. This is not something we can resolve immediately, but we do have a video production effort afoot. I'll move this over to that team and have documented this issue in a larger internal ticket as part of an update to our Ruby materials.
