### ISSUE TITLE
I can't submit a pull request

### ISSUE THREAD

**Issue by hfeldman23** [learn-co-curriculum/ruby-lecture-fixing-our-broken-program#9]
when trying to push my changes I am getting this error. And because of this I'm unable to submit any pull request.
ERROR: Permission to learn-co-students/ruby-lecture-fixing-our-broken-program-001-prework-web.git denied to hfeldman23.
Thanks,
Henry Feldman

**Comment by JessRudder** [comment]
@hfeldman23 it looks like you might not have forked before you cloned the repo.  It's trying to push to learn-co-students/ruby-lecture... instead of hfeldman23/ruby-lecture-....

To fix this, fork the lab then copy your ssh link for your fork.

Then, in terminal (in the directory for this lab) type:

```
git remote add upstream <ssh url>
```

Replace <ssh url> with the url you just copied for your fork.

Then, you should be able to push your changes by typing:

```
git push upstream master
```

**Comment by AnnJohn** [comment]
closing
